# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "themes_for_rails"
  s.version = "1.0.0rc1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lucas Florio"]
  s.date = "2011-11-16"
  s.description = "It allows an application to have many different ways of rendering static assets and dynamic views."
  s.email = "lucasefe@gmail.com"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "README.textile",
    "Rakefile",
    "init.rb",
    "lib/generators/themes_for_rails/install_generator.rb",
    "lib/generators/themes_for_rails/templates/README",
    "lib/generators/themes_for_rails/templates/theme/assets/images/.gitkeep",
    "lib/generators/themes_for_rails/templates/theme/assets/javascripts/.gitkeep",
    "lib/generators/themes_for_rails/templates/theme/assets/javascripts/application.js",
    "lib/generators/themes_for_rails/templates/theme/assets/stylesheets/.gitkeep",
    "lib/generators/themes_for_rails/templates/theme/assets/stylesheets/application.css",
    "lib/generators/themes_for_rails/templates/theme/views/layouts/.gitkeep",
    "lib/generators/themes_for_rails/theme_generator.rb",
    "lib/tasks/themes_for_rails.rake",
    "lib/themes_for_rails.rb",
    "lib/themes_for_rails/assets_finder.rb",
    "lib/themes_for_rails/common_methods.rb",
    "lib/themes_for_rails/config.rb",
    "lib/themes_for_rails/controller_methods.rb",
    "lib/themes_for_rails/logging.rb",
    "lib/themes_for_rails/mailer_methods.rb",
    "lib/themes_for_rails/railtie.rb",
    "lib/themes_for_rails/routes.rb",
    "lib/themes_for_rails/version.rb",
    "lib/themes_for_rails/view_helpers.rb",
    "spec/controllers/my_controller_spec.rb",
    "spec/dummy/.gitignore",
    "spec/dummy/Gemfile",
    "spec/dummy/Gemfile.lock",
    "spec/dummy/README",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/images/rails.png",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/mailers/.gitkeep",
    "spec/dummy/app/models/.gitkeep",
    "spec/dummy/app/themes/default/assets/images/rails.png",
    "spec/dummy/app/themes/default/assets/javascripts/application.js",
    "spec/dummy/app/themes/default/assets/stylesheets/application.css",
    "spec/dummy/app/themes/default/views/layouts/application.html.erb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/seeds.rb",
    "spec/dummy/doc/README_FOR_APP",
    "spec/dummy/lib/assets/.gitkeep",
    "spec/dummy/lib/tasks/.gitkeep",
    "spec/dummy/log/.gitkeep",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/index.html",
    "spec/dummy/public/robots.txt",
    "spec/dummy/script/rails",
    "spec/dummy/test/fixtures/.gitkeep",
    "spec/dummy/test/functional/.gitkeep",
    "spec/dummy/test/integration/.gitkeep",
    "spec/dummy/test/performance/browsing_test.rb",
    "spec/dummy/test/test_helper.rb",
    "spec/dummy/test/unit/.gitkeep",
    "spec/dummy/vendor/assets/stylesheets/.gitkeep",
    "spec/dummy/vendor/plugins/.gitkeep",
    "spec/lib/assets_finder_spec.rb",
    "spec/lib/common_methods_spec.rb",
    "spec/lib/config_spec.rb",
    "spec/lib/controller_methods_spec.rb",
    "spec/lib/view_helpers_spec.rb",
    "spec/mailers/mailer_methods_spec.rb",
    "spec/spec_helper.rb",
    "test/dummy_app/Gemfile.lock",
    "test/dummy_app/log/development.log",
    "test/dummy_app/log/test.log",
    "themes_for_rails.gemspec"
  ]
  s.homepage = "http://github.com/lucasefe/themes_for_rails"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Themes support for rails (3)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<themes_for_rails>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["~> 3.1"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.1.0"])
    else
      s.add_dependency(%q<themes_for_rails>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.1"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.1.0"])
    end
  else
    s.add_dependency(%q<themes_for_rails>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.1"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.1.0"])
  end
end

