# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "themes_for_rails"
  s.version = "1.0.0rc1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lucas Florio"]
  s.date = "2011-11-16"
  s.description = "It allows an application to have many different ways of rendering static assets and dynamic views."
  s.email = "lucasefe@gmail.com"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "README.textile",
    "Rakefile",
    "init.rb",
    "lib/generators/themes_for_rails/install_generator.rb",
    "lib/generators/themes_for_rails/templates/theme/views/layouts/.gitkeep",
    "lib/generators/themes_for_rails/theme_generator.rb",
    "lib/tasks/themes_for_rails.rake",
    "lib/themes_for_rails.rb",
    "lib/themes_for_rails/common_methods.rb",
    "lib/themes_for_rails/config.rb",
    "lib/themes_for_rails/controller_methods.rb",
    "lib/themes_for_rails/mailer_methods.rb",
    "lib/themes_for_rails/railtie.rb",
    "lib/themes_for_rails/routes.rb",
    "lib/themes_for_rails/version.rb",
    "lib/themes_for_rails/view_helpers.rb",
    "themes_for_rails.gemspec"
  ]
  s.homepage = "http://github.com/lucasefe/themes_for_rails"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Themes support for rails (3)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<themes_for_rails>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["~> 3.1"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.0"])
    else
      s.add_dependency(%q<themes_for_rails>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.1"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.0.0"])
    end
  else
    s.add_dependency(%q<themes_for_rails>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.1"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.0.0"])
  end
end

