# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{theme_support}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lucas Florio"]
  s.date = %q{2010-09-10}
  s.description = %q{A different and possibly longer explanation of}
  s.email = %q{lucasefe@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "README.textile",
     "init.rb",
     "lib/tasks/theme_support.rake",
     "lib/theme_support.rb",
     "lib/theme_support/assets_controller.rb",
     "lib/theme_support/railtie.rb",
     "lib/theme_support/routes.rb",
     "lib/theme_support/version.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/lucasefe/theme_support}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{One line summary of your gem}
  s.test_files = [
    "spec/spec_helper.rb",
     "test/dummy_app/app/controllers/application_controller.rb",
     "test/dummy_app/app/helpers/application_helper.rb",
     "test/dummy_app/config/application.rb",
     "test/dummy_app/config/boot.rb",
     "test/dummy_app/config/environment.rb",
     "test/dummy_app/config/environments/development.rb",
     "test/dummy_app/config/environments/production.rb",
     "test/dummy_app/config/environments/test.rb",
     "test/dummy_app/config/initializers/backtrace_silencers.rb",
     "test/dummy_app/config/initializers/inflections.rb",
     "test/dummy_app/config/initializers/mime_types.rb",
     "test/dummy_app/config/initializers/secret_token.rb",
     "test/dummy_app/config/initializers/session_store.rb",
     "test/dummy_app/config/routes.rb",
     "test/dummy_app/db/seeds.rb",
     "test/routes_test.rb",
     "test/support/extensions.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

